### ISSUE TITLE
Product home page gone?

### ISSUE THREAD

**Issue by attritionorg** [vadz/libtiff#1]
For the last 3 days, http://www.remotesensing.org/libtiff/ is redirecting to http://www.remotesensing.org/. Has the project home page moved?

**Comment by vadz** [comment]
Sorry, I'm not responsible for these pages at all, I'm just mirroring the repository here. I can't do anything about this, please try to contact the maintainers if the pages don't reappear in a few days.

**Comment by attritionorg** [comment]
Understood, appreciate it. I used the contact form three days ago but haven't heard anything.
