### ISSUE TITLE
update from master

### ISSUE THREAD

**Issue by asarubbo** [vadz/libtiff#3]
Hi, recently some changes has been added to the cvs repo. Would you mind to update here? thanks.

**Comment by vadz** [comment]
This repository is updated automatically every week (I could do it more frequently if it really needed...), so all the changes will end up here in a few days at most.

**Comment by asarubbo** [comment]
> (I could do it more frequently if it really needed...)

Since I'm working on it (fuzzing each binary provided by tiff), I really appreciate if you can do a daily update, to obtain the git commit which fixes the issue.
I'm not asking to do it forever, but just for the next 2/3 weeks.
Thanks

**Comment by vadz** [comment]
OK, I've changed the cron job to run daily (and also just ran it).
